### PR TITLE
Code clean up

### PR DESCRIPTION
**Pull request by sgnagnarella**
Implemented RAG with Context
Updated gitignore and removed autogenerated files.

### CODE REVIEW

**Comment by nohe427** [comment]
Do folks need to run anything to get the `genkit/compass-generated` files to appear?

**Review by nohe427 — APPROVED** [review]
LGTM, with note

**Comment by sgnagnarella** [comment]
> Do folks need to run anything to get the `genkit/compass-generated` files to appear?

Ugh, they only get generated if you edit an FDC file. Re adding in the next commit. Sorry about that.

**Comment by nohe427** [comment]
No worries. Thanks for taking a second look

**Pull request closed without merging**
